[package]
name = "example-stm32h7"
version = "0.1.0"
authors = ["paopaozhi"]

[dependencies.drivers]
cmsis_device_h7 = { url = "https://github.com/STMicroelectronics/cmsis_device_h7"}
stm32h7xx_hal_driver = { url = "https://github.com/STMicroelectronics/stm32h7xx_hal_driver"}

[dependencies.third_party]
lvgl = {url = "https://github.com/lvgl/lvgl",version = "8.13.0"}